services:
  - type: web
    name: segpredict-ml-dashboard
    runtime: docker
    plan: free
    healthCheckPath: /docs
    autoDeployTrigger: commit
    envVars:
      - key: DEMO_MODE
        value: "true"
